# Generated by Django 6.0.4 on 2026-05-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabticator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('phone', models.IntegerField()),
                ('website', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('fine_art', 'Fine Art'), ('graphic_art', 'Graphic Art'), ('papeterie', 'Papeterie'), ('art_craft', 'Art Craft')], max_length=50)),
                ('price', models.FloatField()),
                ('fabricator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='find_it.fabticator')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='find_it.store')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=150)),
                ('city', models.CharField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='find_it.store')),
            ],
        ),
    ]
