# Generated by Django 6.0.4 on 2026-07-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0002_product_creator_store_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fabricator',
        ),
        migrations.AddField(
            model_name='product',
            name='fabricator',
            field=models.ManyToManyField(to='find_it.fabticator'),
        ),
    ]
