# Generated by Django 6.0.4 on 2026-08-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_it', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
